### ISSUE TITLE
if walder is running and the data changes, the data isn't refetched and the query doesn't re-run, even with --no-cache option'

### ISSUE THREAD

**Issue by bjdmeest** [KNowledgeOnWebScale/walder#23]

**Comment by bjdmeest** [comment]
Specifically, I am hosting my data on the walder instance itself, so basically `http://localhost:3000/data/test.ttl` :)

**Comment by pheyvaer** [comment]
This seems like a bug because `--no-cache` should create a new Comunica instance for every new request.

**Comment by bjdmeest** [comment]
Maybe there's also a cache for you static files it interferes with?

**Comment by bjdmeest** [comment]
I currently fixed it for my development stack using npm-watch that reloads walder everytime I change the config.yaml (which typically goes hand in hand with changed my test data), see my package.json below

```json
{
  "watch": {
    "run": "config.yaml"
  },
  "scripts": {
    "run": "walder -c config.yaml --no-cache",
    "watch": "npm-watch"
  },
  "dependencies": {
    "walder": "^2.0.1"
  },
  "devDependencies": {
    "npm-watch": "^0.7.0"
  }
}


```

**Comment by pheyvaer** [comment]
This fix is actually something nice to put in the README :smile: Maybe something for a PR? :see_no_evil:

**Comment by pheyvaer** [comment]
Use 
```
myEngine.comunicaEngine.invalidateHttpCache();
```
instead of creating an new engine. Tested outside of Walder.
