### ISSUE TITLE
404 error on /favicon.ico in examples

### ISSUE THREAD

**Issue by thomas-delva** [KNowledgeOnWebScale/walder#31]
# Description
When loading or hard-refreshing an example page, `GET /favicon.ico 404` shows up in the logs and the site is also loaded without a favicon

# How to reproduce
1. Start Walder version 2.0.2 with the command `yarn start -c example/config.yaml -l debug --no-cache`
2.  Surf to <http://localhost:3000/music/David%20Bowie> 
3. Optionally refresh without using the cache (Ctrl-F5 in firefox).

**Comment by pheyvaer** [comment]
Yeah indeed. That's because the browser asks for the favicon on its own behalf. We could add a dummy favicon to get rid of the error.
