### ISSUE TITLE
methods in classes derived from base classes do not obey the interface of their base classes (only rdf-converter.js left to correct)

### ISSUE THREAD

**Issue by mvanbrab** [KNowledgeOnWebScale/walder#58]
Seen for classes derived from
- Validator
- Converter

Deviations:
- static (or not)
- async (or not)
- parameter list
- using `this` from a static method to reach another static method in the same class

**Comment by mvanbrab** [comment]
While working on #48 fix, cleaned up for Validator already (now named SubValidator).

**Comment by pheyvaer** [comment]
Why already in that branch though?

**Comment by mvanbrab** [comment]
Because of interference with requested fixes in that branch.

**Comment by pheyvaer** [comment]
Is this actually resolved already?

**Comment by mvanbrab** [comment]
Validator (now SubValidator) and derivatives is OK, Converter and derivatives is not OK.

**Comment by mvanbrab** [comment]
After #86 was fixed, only rdf-converter.js still to do.

**Comment by pheyvaer** [comment]
Fixed in v2.2.0
