### ISSUE TITLE
Work out application profile for publications and projects

### ISSUE THREAD

**Issue by pietercolpaert** [KNowledgeOnWebScale/walder#70]
When working on projects and having publications, I think all of our researchers should add this to their own website, and walder should be able to scrape this. We should work out an application profile for scholarly communications

**Comment by pheyvaer** [comment]
Do you mean a SHACL shape then?

**Comment by mvanbrab** [comment]
We could start from a documentation snippet and end up with a SHACL shape finally.
@pietercolpaert I would suggest to move this issue to the knows-site repo (it's about the data, not about the coder, right?)
