### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by pheyvaer** [KNowledgeOnWebScale/walder#83]
The heap space keeps growing and growing as more request are done. Noticed this via the KNoWS website.

**Comment by mvanbrab** [comment]
@pheyvaer What are the command line options used to run walder for the KNoWS website on the server; `-l debug --no-cache --lenient`? Will use the same to observe...

**Comment by pheyvaer** [comment]
Yes, indeed.

**Comment by mvanbrab** [comment]
See also
https://github.com/mvanbrab/comunica-test-knows
https://github.com/comunica/comunica/issues/816
https://github.com/comunica/comunica/issues/817

**Comment by pheyvaer** [comment]
Fixed in v2.2.0
